[tasks.default]
alias = "dev"

[tasks.serve]
description = "Serve the app on development"
install_crate = "trunk"
command = "trunk"
args = [
    "serve",
    "--watch",
    "assets",
    "--watch",
    "src",
    "--watch",
    "../components",
    "--watch",
    "../macros",
    "--ignore",
    "assets/dist"
]
workspace = false
cwd = "./app"

[tasks.doc]
description = "Open components documentation"
command = "cargo"
args = ["doc", "--open", "--no-deps"]

[tasks.formats]
description = "Format files"
run_task = { name = ["format-rust", "format-prettier"], parallel = true }
workspace = false

[tasks.tests]
description = "Run tests"
run_task = { name = ["serve-for-tests", "run-tests"], parallel = true }
workspace = false

[tasks.watch-css]
description = "Build CSS with Tailwind on development"
command = "../node_modules/.bin/tailwindcss"
args = [
    "-i",
    "./assets/stylesheet.css",
    "-o",
    "./assets/dist/stylesheet.css",
    "--watch",
    "--no-minify"
]
workspace = false
cwd = "./app"

[tasks.watch-css-for-dev]
# Very dirty copy paste of the previous task to make work with serve
# in parallel because cwd must be different
# see the cargo-make documentation:
# "Setting the task’s current working directory via cwd attribute will
# result in all parallel tasks being affected."
description = "Build CSS with Tailwind on development"
command = "../node_modules/.bin/tailwindcss"
args = [
    "-i",
    "./assets/stylesheet.css",
    "-o",
    "./assets/dist/stylesheet.css",
    "--watch",
    "--no-minify"
]
workspace = false
cwd = "."
private = true

[tasks.dev]
description = "Run the app and watch CSS on development"
run_task = { name = ["serve", "watch-css-for-dev"], parallel = true }
workspace = false

[tasks.builds]
description = "Build the app for production"
install_crate = "trunk"
run_task = { name = ["build-css", "build-wasm"] }
workspace = false

[tasks.build-wasm]
install_crate = "trunk"
command = "trunk"
args = ["build", "--release"]
cwd = "./app"
workspace = false

[tasks.build-css]
command = "../node_modules/.bin/tailwindcss"
args = [
    "-i",
    "./assets/stylesheet.css",
    "-o",
    "./assets/dist/stylesheet.css",
    "--minify"
]
cwd = "./app"
workspace = false

[tasks.run-tests]
command = "npx"
args = ["playwright", "test"]
workspace = false
private = true

[tasks.serve-for-tests]
install_crate = "trunk"
command = "trunk"
args = ["serve", "--watch", ".", "--port", "8081"]
workspace = false
cwd = "./app"
private = true

[tasks.format-rust]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]
workspace = false
private = true

[tasks.format-prettier]
command = "prettier"
args = ["--write", ".", "--ignore-path", ".gitignore"]
workspace = false
private = true
