[package]
name = "simple-icons"
version = { workspace = true }
edition = "2018"
description = "Binding between simple-icons library and Rust"

[lib]
path = "src/lib.rs"

[dependencies]
simple-icons-website-config.workspace = true
nanoserde.workspace = true
unicode-normalization.workspace = true
icu_collator.workspace = true
serde_json.workspace = true
