[package]
name = "simple-icons"
version = { workspace = true }
edition = "2018"
description = "Binding between simple-icons library and Rust"

[lib]
path = "src/lib.rs"

[dependencies]
nanoserde = "0.1"
unicode-normalization = "0.1"
icu_collator = "1.1"
serde_json = "1.0"
