[package]
name = "simple-icons-website"
version = { workspace = true }
edition = "2021"

[dependencies]
simple-icons-website-components = { path = "../components" }
simple-icons-website-macros = { path = "../macros" }
simple-icons-website-i18n = { path = "../i18n" }
leptos = "0.2.5"
leptos_meta = { version = "0.2.5", features = ["csr"] }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["MediaQueryList"] }
