[package]
name = "simple-icons-website"
version = "0.1.0"
edition = "2021"

[dependencies]
components = { path = "../components" }
leptos = "0.2.4"
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2"
