[build]
# TODO: Very ugly fix to make the page serve from paths
# (like in Github pages with default domain) where
# the base url is not the root of the domain. Seems that
# the environment variable TRUNK_PUBLIC_URL and the CLI option
# --public-url are not working:
# https://github.com/thedodd/trunk/issues/395
#
# If you use this configuration with the development server
# it will raise an error from axum with the message
# 'Paths must start with a `/`'
public_url = "./"
