[package]
name = "simple-icons-website-components"
version = { workspace = true }
edition = "2021"
description = "Simple Icons website components"

[lib]
crate-type = ["cdylib", "rlib"]
name = "components"

[dependencies]
simple-icons-website-macros = { path = "../macros" }
simple-icons-website-i18n = { path = "../i18n" }
simple-icons-website-config = { path = "../config" }
simple-icons = { path = "../simple-icons" }
leptos = "0.2.5"
log = "0.4"
web-sys = { version = "0.3", features = [
    "Element",
    "HtmlCollection",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlImageElement",
    "DomTokenList",
    "EventTarget",
    "Storage",
    "Clipboard",
] }
js-sys = "0.3"
wasm-bindgen = "0.2"
rust-fuzzy-search = "0.1"
wasm-bindgen-futures = "0.4"
reqwasm = "0.5"
lazy_static = "1.4"
