[package]
name = "simple-icons-website-components"
version = "0.1.0"
edition = "2021"
description = "Simple Icons website components"

[lib]
crate-type = ["cdylib", "rlib"]
name = "components"

[dependencies]
leptos = "0.2.4"
