[package]
name = "components"
version = "0.1.0"
edition = "2021"
description = "Simple Icons website components"

[lib]
crate-type = ["cdylib", "rlib"]
name = "components"

[dependencies]
leptos = { path = "../../leptos/leptos" }
