[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fetch-deprecated-icons"
path = "src/fetch-deprecated-icons.rs"

[dependencies]
simple-icons-website-config = { path = "../config" }
dotenv = "0.15"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
